name: "Build"
on:
  - "push"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk:
          - 8
          - 11
          - 15
    steps:
      - uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v2
        with:
          java-version: "${{ matrix.jdk }}"
          distribution: "zulu"
      - name: "Build with Gradle"
        run: ./gradlew build
